# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - addressbook-octo-actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://jfrogdev.site/
        username: ${{ secrets.AzureAppService_ContainerUsername_f1194918fd7a4aefbb86eb42051397e9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_18f3e24e40e54b8b8d6b1aeafea0637b }}

    - name: Build with Maven
      run: mvn package -s ./.m2/settings.xml --file pom.xml
      
    - name: Copy war file
      run: cp /home/runner/work/addressbook/addressbook/target/addressbook.war .
      
    - name: List Files
      run: ls      

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jfrogdev.site/${{ secrets.AzureAppService_ContainerUsername_f1194918fd7a4aefbb86eb42051397e9 }}/team1-docker-local/addressbook:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'addressbook-octo-actions'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3582f355270146c09b05b5642fbe0634 }}
        images: 'jfrogdev.site/${{ secrets.AzureAppService_ContainerUsername_f1194918fd7a4aefbb86eb42051397e9 }}/team1-docker-local/addressbook:${{ github.sha }}'
